### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by paulobocanegra** [johnnyhoang510/Smackin#1]
we need to add the markup highlight: `markup example` to every column name and column we are indexing. 

Here is a detailed tutorial:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by johnnyhoang510** [comment]
Hey Paulo, am I supposed to close these myself? I've updated the all issues, if it needs anymore work let me know. Thanks!

**Comment by paulobocanegra** [comment]
Once I see the updates I'll close the issues 😃 
Sorry for the wait, I've been going alphabetically with each student, each wiki page, while taking questions. It should be ready before the assessment is over.

**Comment by paulobocanegra** [comment]
Great job! 💯
